In [35]:
   %load_ext autoreload
   %autoreload 2

   import pandas as pd
   from gasp import eia

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
#Gets all data from lower 48 states
df = eia.fetch_series("NW2_EPG0_SWO_R48_BCF")
df

        period                series   value
0   2010-01-01  NW2_EPG0_SWO_R48_BCF  3117.0
1   2010-01-08  NW2_EPG0_SWO_R48_BCF  2850.0
2   2010-01-15  NW2_EPG0_SWO_R48_BCF  2607.0
3   2010-01-22  NW2_EPG0_SWO_R48_BCF  2521.0
4   2010-01-29  NW2_EPG0_SWO_R48_BCF  2406.0
..         ...                   ...     ...
871 2026-09-11  NW2_EPG0_SWO_R48_BCF  3298.0
872 2026-09-18  NW2_EPG0_SWO_R48_BCF  3351.0
873 2026-09-25  NW2_EPG0_SWO_R48_BCF  3415.0
874 2026-10-02  NW2_EPG0_SWO_R48_BCF  3500.0
875 2026-10-09  NW2_EPG0_SWO_R48_BCF  3567.0

[876 rows x 3 columns]

In [ ]:
#Same but with East Region
df_east = eia.fetch_series('NW2_EPG0_SWO_R31_BCF')
df_east

        period                series  value
0   2010-01-01  NW2_EPG0_SWO_R31_BCF  769.0
1   2010-01-08  NW2_EPG0_SWO_R31_BCF  703.0
2   2010-01-15  NW2_EPG0_SWO_R31_BCF  642.0
3   2010-01-22  NW2_EPG0_SWO_R31_BCF  616.0
4   2010-01-29  NW2_EPG0_SWO_R31_BCF  582.0
..         ...                   ...    ...
871 2026-09-11  NW2_EPG0_SWO_R31_BCF  795.0
872 2026-09-18  NW2_EPG0_SWO_R31_BCF  815.0
873 2026-09-25  NW2_EPG0_SWO_R31_BCF  840.0
874 2026-10-02  NW2_EPG0_SWO_R31_BCF  862.0
875 2026-10-09  NW2_EPG0_SWO_R31_BCF  884.0

[876 rows x 3 columns]

In [ ]:
#Chunks data 100 entries at a time
df_paged = eia.fetch_series("NW2_EPG0_SWO_R48_BCF", page_size=100)
len(df_paged) == len(df), len(df_paged)

(True, 876)

In [ ]:
#Correctly applies start and end 
df_range = eia.fetch_series("NW2_EPG0_SWO_R48_BCF", start="2024-01-01", end="2024-12-31")
df_range

       period                series   value
0  2024-01-05  NW2_EPG0_SWO_R48_BCF  3336.0
1  2024-01-12  NW2_EPG0_SWO_R48_BCF  3182.0
2  2024-01-19  NW2_EPG0_SWO_R48_BCF  2856.0
3  2024-01-26  NW2_EPG0_SWO_R48_BCF  2659.0
4  2024-02-02  NW2_EPG0_SWO_R48_BCF  2584.0
5  2024-02-09  NW2_EPG0_SWO_R48_BCF  2530.0
6  2024-02-16  NW2_EPG0_SWO_R48_BCF  2470.0
7  2024-02-23  NW2_EPG0_SWO_R48_BCF  2374.0
8  2024-03-01  NW2_EPG0_SWO_R48_BCF  2334.0
9  2024-03-08  NW2_EPG0_SWO_R48_BCF  2325.0
10 2024-03-15  NW2_EPG0_SWO_R48_BCF  2332.0
11 2024-03-22  NW2_EPG0_SWO_R48_BCF  2296.0
12 2024-03-29  NW2_EPG0_SWO_R48_BCF  2259.0
13 2024-04-05  NW2_EPG0_SWO_R48_BCF  2283.0
14 2024-04-12  NW2_EPG0_SWO_R48_BCF  2333.0
15 2024-04-19  NW2_EPG0_SWO_R48_BCF  2425.0
16 2024-04-26  NW2_EPG0_SWO_R48_BCF  2484.0
17 2024-05-03  NW2_EPG0_SWO_R48_BCF  2569.0
18 2024-05-10  NW2_EPG0_SWO_R48_BCF  2640.0
19 2024-05-17  NW2_EPG0_SWO_R48_BCF  2719.0
20 2024-05-24  NW2_EPG0_SWO_R48_BCF  2804.0
21 2024-05-31  NW2_EPG0_SWO_R48_BCF  2900.0
22 2024-06-07  NW2_EPG0_SWO_R48_BCF  2974.0
23 2024-06-14  NW2_EPG0_SWO_R48_BCF  3045.0
24 2024-06-21  NW2_EPG0_SWO_R48_BCF  3102.0
25 2024-06-28  NW2_EPG0_SWO_R48_BCF  3134.0
26 2024-07-05  NW2_EPG0_SWO_R48_BCF  3199.0
27 2024-07-12  NW2_EPG0_SWO_R48_BCF  3209.0
28 2024-07-19  NW2_EPG0_SWO_R48_BCF  3231.0
29 2024-07-26  NW2_EPG0_SWO_R48_BCF  3249.0
30 2024-08-02  NW2_EPG0_SWO_R48_BCF  3270.0
31 2024-08-09  NW2_EPG0_SWO_R48_BCF  3264.0
32 2024-08-16  NW2_EPG0_SWO_R48_BCF  3299.0
33 2024-08-23  NW2_EPG0_SWO_R48_BCF  3334.0
34 2024-08-30  NW2_EPG0_SWO_R48_BCF  3347.0
35 2024-09-06  NW2_EPG0_SWO_R48_BCF  3387.0
36 2024-09-13  NW2_EPG0_SWO_R48_BCF  3445.0
37 2024-09-20  NW2_EPG0_SWO_R48_BCF  3493.0
38 2024-09-27  NW2_EPG0_SWO_R48_BCF  3548.0
39 2024-10-04  NW2_EPG0_SWO_R48_BCF  3630.0
40 2024-10-11  NW2_EPG0_SWO_R48_BCF  3706.0
41 2024-10-18  NW2_EPG0_SWO_R48_BCF  3785.0
42 2024-10-25  NW2_EPG0_SWO_R48_BCF  3864.0
43 2024-11-01  NW2_EPG0_SWO_R48_BCF  3931.0
44 2024-11-08  NW2_EPG0_SWO_R48_BCF  3972.0
45 2024-11-15  NW2_EPG0_SWO_R48_BCF  3969.0
46 2024-11-22  NW2_EPG0_SWO_R48_BCF  3967.0
47 2024-11-29  NW2_EPG0_SWO_R48_BCF  3937.0
48 2024-12-06  NW2_EPG0_SWO_R48_BCF  3747.0
49 2024-12-13  NW2_EPG0_SWO_R48_BCF  3622.0
50 2024-12-20  NW2_EPG0_SWO_R48_BCF  3529.0
51 2024-12-27  NW2_EPG0_SWO_R48_BCF  3413.0

In [ ]:
#Is able to get the newest date.
latest = eia.latest_period()
latest, df["period"].max()

(Timestamp('2026-10-09 00:00:00'), Timestamp('2026-10-09 00:00:00'))